name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write
    env:
      RAILS_ENV: test
    strategy:
      fail-fast: true
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run RSpec Tests
        timeout-minutes: 20
        run: bundle exec rspec -f doc
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          bundler-cache: true
          ruby-version: "3.1"
      - name: Bundle Audit Check
        run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
