name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write
    env:
      RAILS_ENV: test
    strategy:
      fail-fast: true
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run RSpec Tests
        timeout-minutes: 20
        run: bundle exec rspec -f doc
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410
        with:
          bundler-cache: true
          ruby-version: "3.3"
      - name: Bundle Audit Check
        run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.12"
      - name: Run pre-commit
        uses: instrumentl/pre-commit-action@v4
